language: node_js
dist: xenial
node_js:
  - 10
  - 8
  - 6
  - 4
sudo: required
addons:
    chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - apt-get install libboost-all-dev
  - npm set progress=false
  - npm install
script:
  - ng lint
  - npm run test
  - npm run e2e
  - npm run build
